- name: URI module test
  hosts: all
  gather_facts: false
  become: false
  vars:
    server: "https://reqres.in"
    endpoint: "api/users/2"
  tasks:
    - name: Liste des utilisateurs
      ansible.builtin.uri:
        url: "{{ server }}/{{ endpoint }}"
        method: GET
        status_code: 200
        return_content: true
        timeout: 30
      register: result

    - name: Debug user payload
      ansible.builtin.debug:
        var: result.json.data
