- name: URI module test
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    server: "https://jsonplaceholder.typicode.com"
    endpoint: "users/1"
  tasks:
    - name: Liste des utilisateurs
      ansible.builtin.uri:
        url: "{{ server }}/{{ endpoint }}"
        method: GET
        status_code: 200
        return_content: true
        timeout: 30
      register: result

    - name: Debug user payload
      ansible.builtin.debug:
        var: result.json
